project:
  type: website

website:
  title: "LaughingRook"
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: ember.scss
    css: styles.css
    toc: true
    toc-depth: 3

execute:
  freeze: auto